# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_rag',
                'doc_host': 'https://antoni0z.github.io',
                'git_url': 'https://github.com/antoni0z/nbdev_rag',
                'lib_path': 'nbdev_rag'},
  'syms': {'nbdev_rag.core': {'nbdev_rag.core.foo': ('core.html#foo', 'nbdev_rag/core.py')}}}
