# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_context.ipynb.

# %% auto 0
__all__ = ['ModelContext']

# %% ../nbs/02_context.ipynb 2
class ModelContext:
    def __init__(self, llm, embedding, tokenizer):
        self.llm = llm
        self.embedding = embedding
        self.tokenizer = tokenizer
        
