# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_store.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/03_store.ipynb 2
from .base import Document, abstractmethod, ABC
from typing import Union, List, Dict
from uuid import UUID
